[package]
name = "cargo-gh-pages"
version = "0.1.0"
authors = ["Ning Sun <sunng@about.me>", "Pascal Hartig <i@passy.me>", "Daithi O Crualaoich <daithi.ocrualaoich@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Cargo gh-pages command."
keywords = ["cargo"]
repository = "https://github.com/woofwoofinc/cargo-gh-pages"

[dependencies]
toml = "0.2.0"
quick-error = "1.1.0"
clap = "2.10.4"

[package.metadata.release]
sign-commit = false
push-remote = "origin"
doc-branch = "gh-pages"
doc-commit-message = "(cargo-gh-pages) Generate docs."
